### ISSUE TITLE
Review default transaction payload (data field)

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb-common#21]
This concerns cases for which the payload is `None`, when creating a transaction, e.g.:

``` python
tx = Transaction.create(owners_before, owners_after, payload=None)
```

The new behaviour makes it so that transactions without payloads and duplicate timestamps, created within a loop for instance, will hash to the same value. The legacy behaviour was such that a **`uuid`** would be generated for the `data` field, regardless of whether the payload was `None` or not, which would prevent duplicate hashes.

The ["legacy" behaviour](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/util.py#L226-LL229) was: 

``` python
data = {
    'uuid': str(uuid.uuid4()),
    'payload': payload
}
```

regardless of whether `payload` is `None` or not.

This would give something like:

``` python
ipdb> pp tx.to_dict()['transaction']['data']
{
    'uuid': 'asdghasgdfds...',
    'payload': None
}
```

The [new behaviour](https://github.com/bigchaindb/bigchaindb-common/blob/master/bigchaindb_common/transaction.py#L256-L263) is given by:

``` python
    def to_dict(self):
        if self.payload is None:
            return None
        else:
            return {
                'payload': self.payload,
                'uuid': self.payload_id,
            }
```

which gives:

``` python
ipdb> pp tx.to_dict()['transaction']['data']
None
```

**Comment by TimDaub** [comment]
@r-marques might wanna comment on this with respect to the digital assets implementation.

**Comment by r-marques** [comment]
Before the asset implementation if you did not have a uuid in the payload and create several transactions in a short amount of time you would end up with duplicated transactions (same txid) because the actual content of the transactions would be the same.

This may no longer be true after the asset implementation.
We should revisit this once the asset integration is finished.

**Comment by sbellem** [comment]
Just to be sure it is clear: 

as of now -- ([current master branch](https://github.com/bigchaindb/bigchaindb/tree/1ae08990c80e9bd560d759c2b04c871d36886e61)) -- there is a possibility of having duplicate hashes when creating multiple transactions within a small time range, such that timestamps do not differ.

This is basically a regression from the previous behaviour, in which a default **`uuid`** was created whenever the payload was `None`.

**Comment by ttmc** [comment]
As I understand it, the soon-to-arrive digital asset model (see https://github.com/bigchaindb/bigchaindb/issues/125 ) will make it so that no two transactions will ever have the same hash (id), regardless of what is in the data/payload/metadata. One reason is that the `transaction.metadata.id` in a transaction will be a different random UUID for every transaction (i.e. a random string, not a hash).

**Comment by TimDaub** [comment]
> One reason is that the transaction.metadata.id in a transaction will be a different random UUID for every transaction (i.e. a random string, not a hash).

Exactly right. Since #25 was merged just now, this ticket has been resolved.
